# Generated by Django 4.2.20 on 2025-06-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine_tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedTweetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_tweet', models.TextField()),
                ('factual_tweet', models.TextField()),
                ('rant_tweet', models.TextField()),
                ('extracted_urls', models.JSONField(default=list)),
                ('popularity_score', models.JSONField(blank=True, null=True)),
                ('safety_score', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'combined_tweet_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
