# Generated by Django 5.2 on 2025-04-16 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_api_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to="twitter_api_app.twitteruser",
            ),
        ),
    ]
