# Generated by Django 5.1.7 on 2025-03-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("protected", models.BooleanField(default=False)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("tweet_count", models.IntegerField(default=0)),
                ("listed_count", models.IntegerField(default=0)),
                (
                    "last_pagination_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50, unique=True)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("retweet_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("quote_count", models.IntegerField(default=0)),
                ("impression_count", models.IntegerField(blank=True, null=True)),
                ("url_link_clicks", models.IntegerField(blank=True, null=True)),
                ("user_profile_clicks", models.IntegerField(blank=True, null=True)),
                ("bookmark_count", models.IntegerField(blank=True, null=True)),
                ("hashtags", models.JSONField(blank=True, null=True)),
                ("mentions", models.JSONField(blank=True, null=True)),
                ("urls", models.JSONField(blank=True, null=True)),
                ("symbols", models.JSONField(blank=True, null=True)),
                ("possibly_sensitive", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to="app.twitteruser",
                    ),
                ),
            ],
        ),
    ]
