# Generated by Django 5.2 on 2025-04-29 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarbonRantTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("content", models.TextField()),
                ("tweet_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), blank=True, null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "carbonrant_tweets",
            },
        ),
        migrations.CreateModel(
            name="CarbonSustainAITweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("content", models.TextField()),
                ("tweet_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), blank=True, null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "carbonsustainai_tweets",
            },
        ),
        migrations.CreateModel(
            name="CarbonTruthTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("content", models.TextField()),
                ("tweet_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), blank=True, null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "carbontruth_tweets",
            },
        ),
        migrations.CreateModel(
            name="DefaultTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("content", models.TextField()),
                ("tweet_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), blank=True, null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "default_tweets",
            },
        ),
    ]
