# Generated by Django 5.2 on 2025-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elizaservicesapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "bot",
                    models.CharField(
                        choices=[
                            ("carbontruth", "CarbonTruth"),
                            ("carbonsustainai", "CarbonSustainAI"),
                            ("carbonrant", "CarbonRant"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("news", "News"), ("personal", "Personal")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("when_to_post", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "db_table": "queued_tweets",
            },
        ),
    ]
