# Generated by Django 5.2 on 2025-06-10 05:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elizaservicesapi", "0002_queuedtweet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuedtweet",
            name="title",
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="content",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("posted", "Posted"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
