# Generated by Django 5.2 on 2025-06-11 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elizaservicesapi",
            "0003_remove_queuedtweet_title_alter_queuedtweet_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedtweet",
            name="date",
            field=models.DateField(default="2025-06-11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="time",
            field=models.TimeField(default="14:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="tweet_id",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="content",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("posted", "Posted")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
