# Generated by Django 5.2 on 2025-06-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elizaservicesapi", "0004_queuedtweet_date_queuedtweet_hashtags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuedtweet",
            name="tweet_id",
        ),
    ]
