# Generated by Django 5.2 on 2025-06-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elizaservicesapi", "0005_remove_queuedtweet_tweet_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuedtweet",
            name="date",
        ),
        migrations.RemoveField(
            model_name="queuedtweet",
            name="time",
        ),
    ]
