# Generated by Django 5.2 on 2025-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elizaservicesapi", "0006_remove_queuedtweet_date_remove_queuedtweet_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carbonranttweet",
            name="date",
        ),
        migrations.RemoveField(
            model_name="carbonranttweet",
            name="time",
        ),
        migrations.RemoveField(
            model_name="carbonsustainaitweet",
            name="date",
        ),
        migrations.RemoveField(
            model_name="carbonsustainaitweet",
            name="time",
        ),
        migrations.RemoveField(
            model_name="carbontruthtweet",
            name="date",
        ),
        migrations.RemoveField(
            model_name="carbontruthtweet",
            name="time",
        ),
        migrations.RemoveField(
            model_name="defaulttweet",
            name="date",
        ),
        migrations.RemoveField(
            model_name="defaulttweet",
            name="time",
        ),
        migrations.AlterField(
            model_name="carbonranttweet",
            name="tweet_link",
            field=models.URLField(
                default="https://x.com/carbonsustainai/status/1899869504521592993",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carbonsustainaitweet",
            name="tweet_link",
            field=models.URLField(
                default="https://x.com/carbonsustainai/status/1899869504521592993",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carbontruthtweet",
            name="tweet_link",
            field=models.URLField(
                default="https://x.com/carbonsustainai/status/1899869504521592993",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="defaulttweet",
            name="tweet_link",
            field=models.URLField(
                default="https://x.com/carbonsustainai/status/1899869504521592993",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
