# Generated by Django 5.2 on 2025-06-15 04:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("elizaservicesapi", "0007_remove_carbonranttweet_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuedtweet",
            name="status",
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="image_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="bot",
            field=models.CharField(
                choices=[
                    ("carbontruth", "CarbonTruth"),
                    ("carbonsustainai", "CarbonSustainAI"),
                    ("carbonrant", "CarbonRant"),
                    ("default", "DefaultBot"),
                ],
                max_length=30,
            ),
        ),
    ]
